# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b2eaf8cd6b34989dcf1ac0d4a3547cd99ef0ebbefa3d2f5d2cce71aad173663976eb9f8fe42c70dfd268c583bc7d4d003cffcef31b8572e81f079648e36553f

test:
  secret_key_base: 38e9044728178eee494dd64c3f21107ba65c1d85e8d05f1fd7b9e6062d370737fb237c8b606bf4b7ad943d2dec5051f1c07f375a3b79ddb18163c4851e141023

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
